jobs:
  include:
    - os: linux
      dist: focal
      language: python
      vault:
        api_url: https://vault-dwztla.travis-ci.com
        token: 
          secure: "B5y/RFp+tpJK5qXrVGbGdTc8pAvnguRxwwKENj5VSdP1uy7KxoVUnNLhDrDr2Ngs8/RZ/92a2UP0yXct0+wtGdZKNhtxGFpccmFf5I8YuKtT1fk+JZWVOKuGrYsuYSAhUfRk/bDj0koXkTUJO0m9k9UHBGkOgjciZC9TU7FNNAy1vF/br5l3vigrFovbY+h3WIEiuoIn4wSERbLAosMgS9fZXsCFpj3sySH6qgx2CODmzUFunImNopoRfEFqN/9DkswVYgBDAkhCJU65CarEvLLq3V9wm+zM4+eHIozcFL0XnS8eevcprfM35DJQXHEcnhPvpb38VZrM9X9NCEwg8V9W5pwfD/XGzvlrs8+CJTwtRgddoUMMDjJepUhNIAC0cK4tDNlFZ3Ebc7gmbHjyOI19114LWCH7UPsu5Co+2cSl9K1A0sUag1vQlsuGgmbE5/1poisT1RYxN2u/cLvw+GC1PmVLXSa2k9LMA6v6Ya+6b8l1xkRunGh9qmtSoEfT+efrJkOkmXlh8MQwRjUNyOLlYh1yLW5G0p6nq77pYsbu6ktZXFIA03h3BxZTLRwDahvUbabcJGX3dBxIOPaXjB0b4ce3H1OMomwLUYIp8rZKyB70i33s1bNNqyKx6VFwAqFxGBMy3V+de+0xLmaqgWYaSJTDpwbDld3gr2aWw8E="
        secrets:
          - kv_api_ver: kv2
#           - namespace:
#             - name: ns1
#             - language_used/compiler
          - ns1/language_used
          - ns1/language_used/compiler
#           - ns2/project_id/secret_key_b
      script:
        - echo $LANGUAGE_USED
        - echo $COMPILER
